//   THIS FILE HAS NO CODE IN IT, BUT YOUR housing.cpp WILL
//   NOT COMPILE WITHOUT IT. (WE USE ANOTHER VERION OF THIS
//   FILE THAT DOES HAVE CODE IN IT WHEN WE TEST YOUR
//   SUBMISSION.) SO, PLEASE LEAVE THIS FILE
//   EXACTLY AS IT IS.
